name: Setup Vapoursynth
description: Setup Vapoursynth in the current runner

inputs:
  vs-version:
    description: Vapoursynth version to use, defaults to latest
    required: true
    default: R62 # renovate: datasource=pypi dep_name=vapoursynth

runs:
  using: composite
  steps:
    - name: Install vapoursynth make-deps
      if: runner.os == 'linux'
      shell: bash
      run: sudo apt install cython3 libzimg-dev

    - name: Install vapoursynth make-deps
      if: runner.os == 'macos'
      shell: bash
      run: |
        brew install automake zimg coreutils
        pip3 install cython

    - name: Cache vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      id: cache-vs
      uses: actions/cache@v3
      with:
        path: ./vapoursynth
        key: vs-${{ runner.os }}-${{ inputs.vs-version }}

    - name: Make vapoursynth
      if: (runner.os == 'linux' || runner.os == 'macos') && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      run: |
        echo $(nproc)
        git clone https://github.com/vapoursynth/vapoursynth --depth 1 -b ${{ inputs.vs-version }}
        pushd vapoursynth
        rm -rf .git installer doc msvc_project
        ./autogen.sh
        if [ ${{ runner.os }} == 'linux' ]; then
          ./configure --prefix=/usr --disable-x86-asm --disable-vspipe
        elif [ ${{ runner.os }} == 'macos' ]; then
          ./configure --disable-x86-asm --disable-vspipe
        fi
        make -j$(nproc)

    - name: Install vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      run: |
        echo $(nproc)
        pushd vapoursynth
        sudo make install -j$(nproc)
        popd
      # rm -rf vapoursynth

branding:
  icon: video
  color: gray-dark
