name: Install Vapoursynth
description: Install Vapoursynth in the current runner

inputs:
  version:
    description: Vapoursynth version to use, defaults to latest
    required: true
    default: R62 # renovate: datasource=pypi dep_name=vapoursynth

runs:
  using: composite
  steps:
    - name: Install vapoursynth make-deps
      if: runner.os == 'linux'
      shell: bash
      run: sudo apt install cython3 g++ libzimg-dev ninja-build
      # meson

    - name: Echo CC and CXX
      shell: bash
      run: |
        echo $CC
        echo $CXX

    - name: Install vapoursynth make-deps
      if: runner.os == 'macos'
      shell: bash
      run: |
        brew install cython gcc zimg meson ninja automake
        pip install cython

    - name: Use ccache
      if: runner.os == 'linux' || runner.os == 'macos'
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ runner.os }}-${{ inputs.version }}

    - name: Echo CC and CXX
      shell: bash
      run: |
        echo $CC
        echo $CXX

    - name: Configure shell
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      run: echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV

    - name: Install vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --depth 1 -b ${{ inputs.version }}
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr --disable-x86-asm --disable-vspipe
        make -j2
        sudo make install -j2
        popd
        rm -rf vapoursynth
