name: Setup Vapoursynth
description: Setup Vapoursynth in the current runner

inputs:
  vs-version:
    description: Vapoursynth version to use, defaults to latest
    required: true
    default: "73" # renovate: datasource=pypi dep_name=vapoursynth
  cython-version:
    description: Cython version to use, defaults to latest
    required: true
    default: "3.1.4" # renovate: datasource=pypi dep_name=cython
  zimg-version:
    description: Zimg version to use, defaults to latest
    required: true
    default: "v3.0.5" # renovate: datasource=github-releases dep_name=sekrit-twc/zimg

runs:
  using: composite
  steps:
    - name: Cache vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      id: cache-vs
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-vs-${{ inputs.vs-version }}
        path: |
          /tmp/vapoursynth/*
          !/tmp/vapoursynth/.git
          !/tmp/vapoursynth/doc
          !/tmp/vapoursynth/installer
          !/tmp/vapoursynth/msvc_project

    - name: Cache zimg
      if: runner.os == 'linux' || runner.os == 'macos'
      id: cache-zimg
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-zimg-${{ inputs.zimg-version }}
        path: |
          /tmp/zimg/*
          !/tmp/zimg/.git
          !/tmp/zimg/_msvc

    - name: Set env vars
      id: set-env
      shell: bash
      run: |
        if [[ "${RUNNER_OS,,}" = "linux" ]]; then
          echo "cores=$(nproc)" >> $GITHUB_OUTPUT
          echo "prefix=/usr" >> $GITHUB_OUTPUT
        elif [[ "${RUNNER_OS,,}" = "macos" ]]; then
          echo "cores=$(sysctl -n hw.ncpu)" >> $GITHUB_OUTPUT
          echo "prefix=/usr/local" >> $GITHUB_OUTPUT
        fi

    - name: Install cython
      if: runner.os == 'linux' && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      env:
        CYTHON_VERSION: ${{ inputs.cython-version }}
      run: pip3 install "cython==${CYTHON_VERSION}"

    - name: Install cython
      if: runner.os == 'macos' && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      env:
        CYTHON_VERSION: ${{ inputs.cython-version }}
      run: pip3 install --break-system-packages "cython==${CYTHON_VERSION}"

    - name: Install automake
      if: runner.os == 'macos' && (steps.cache-vs.outputs.cache-hit != 'true' || steps.cache-zimg.outputs.cache-hit != 'true')
      shell: bash
      run: brew install automake libtool

    - name: Make zimg
      if: (runner.os == 'linux' || runner.os == 'macos') && steps.cache-zimg.outputs.cache-hit != 'true'
      shell: bash
      env:
        ZIMG_VERSION: ${{ inputs.zimg-version }}
        CORES: ${{ steps.set-env.outputs.cores }}
        PREFIX: ${{ steps.set-env.outputs.prefix }}
      run: |
        git clone https://github.com/sekrit-twc/zimg /tmp/zimg --depth 1 -b release-${ZIMG_VERSION//v/}
        cd /tmp/zimg
        ./autogen.sh
        ./configure --prefix=${PREFIX}
        make -j${CORES}

    - name: Install zimg
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      env:
        CORES: ${{ steps.set-env.outputs.cores }}
      run: |
        cd /tmp/zimg
        sudo make install -j${CORES}

    - name: Make vapoursynth
      if: (runner.os == 'linux' || runner.os == 'macos') && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      env:
        VS_VERSION: ${{ inputs.vs-version }}
        CORES: ${{ steps.set-env.outputs.cores }}
        PREFIX: ${{ steps.set-env.outputs.prefix }}
      run: |
        git clone https://github.com/vapoursynth/vapoursynth /tmp/vapoursynth --depth 1 -b R${VS_VERSION}
        cd /tmp/vapoursynth
        ./autogen.sh
        ./configure --prefix=${PREFIX} --disable-x86-asm --disable-vspipe
        make -j${CORES}

    - name: Install vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      env:
        CORES: ${{ steps.set-env.outputs.cores }}
      run: |
        cd /tmp/vapoursynth
        sudo make install -j${CORES}

branding:
  icon: video
  color: gray-dark
