name: Setup Vapoursynth
description: Setup Vapoursynth in the current runner

inputs:
  vs-version:
    description: Vapoursynth version to use, defaults to latest
    required: true
    default: R65 # renovate: datasource=pypi dep_name=vapoursynth
  cython-version:
    description: Cython version to use, defaults to latest
    required: true
    default: 3.0.9 # renovate: datasource=pypi dep_name=cython
  zimg-version:
    description: Zimg version to use, defaults to latest
    required: true
    default: release-3.0.4 # renovate: datasource=github-releases dep_name=sekrit-twc/zimg

runs:
  using: composite
  steps:
    - name: Cache vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      id: cache-vs
      uses: actions/cache@v4
      with:
        key: vs-${{ runner.os }}-${{ inputs.vs-version }}
        path: |
          /tmp/vapoursynth/*
          !/tmp/vapoursynth/.git
          !/tmp/vapoursynth/doc
          !/tmp/vapoursynth/installer
          !/tmp/vapoursynth/msvc_project

    - name: Set env vars
      if: runner.os == 'linux'
      shell: bash
      run: |
        echo "CORES=$(nproc)" >> $GITHUB_ENV
        echo "PREFIX=/usr" >> $GITHUB_ENV

    - name: Set env vars
      if: runner.os == 'macos'
      shell: bash
      run: |
        echo "CORES=$(sysctl -n hw.ncpu)" >> $GITHUB_ENV
        echo "PREFIX=/usr/local" >> $GITHUB_ENV

    - name: Install vapoursynth deps
      if: runner.os == 'linux'
      shell: bash
      run: sudo apt install libzimg-dev

    - name: Install vapoursynth deps
      if: runner.os == 'macos'
      shell: bash
      run: brew install zimg

    - name: Install vapoursynth make-deps
      if: runner.os == 'linux' && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      run: pip3 install "cython==${{ inputs.cython-version }}"

    - name: Install vapoursynth make-deps
      if: runner.os == 'macos' && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      run: |
        brew install automake
        pip3 install "cython==${{ inputs.cython-version }}"

    - name: Make vapoursynth
      if: (runner.os == 'linux' || runner.os == 'macos') && steps.cache-vs.outputs.cache-hit != 'true'
      shell: bash
      run: |
        git clone https://github.com/vapoursynth/vapoursynth /tmp/vapoursynth --depth 1 -b ${{ inputs.vs-version }}
        cd /tmp/vapoursynth
        ./autogen.sh
        ./configure --prefix=$PREFIX --disable-x86-asm --disable-vspipe
        make -j$CORES

    - name: Install vapoursynth
      if: runner.os == 'linux' || runner.os == 'macos'
      shell: bash
      run: |
        cd /tmp/vapoursynth
        sudo make install -j$CORES

branding:
  icon: video
  color: gray-dark
