name: Install Vapoursynth
description: Install Vapoursynth in the current runner
inputs:
  version:
    description: Vapoursynth version to use, if version is not provided then latest stable version will be used
    required: true
    default: 62
runs:
  runs-on: ubuntu-latest
  steps:
    - name: Install vapoursynth make-deps
      run: sudo apt install cython3 g++ libzimg-dev meson ninja-build

    - name: Use ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: R${{ inputs.version }}

    - name: Configure shell
      run: echo 'PATH=/usr/lib/ccache:'"$PATH" >> $GITHUB_ENV

    - name: Install vapoursynth
      run: |
        git clone https://github.com/vapoursynth/vapoursynth --depth 1 -b R${{ inputs.version }}
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-x86-asm --disable-vspipe
        make -j2
        sudo make install -j2
        popd
        rm -rf vapoursynth
