name: Install Vapoursynth
description: Install Vapoursynth in the current runner

inputs:
  vs-version:
    description: Vapoursynth version to use, defaults to latest
    required: true
    default: R62 # renovate: datasource=pypi dep_name=vapoursynth

runs:
  using: composite
  steps:
    - name: Install vapoursynth make-deps
      if: runner.os == 'linux'
      shell: bash
      run: sudo apt install cython3 libzimg-dev

    - name: Install vapoursynth make-deps
      if: runner.os == 'macos'
      shell: bash
      run: |
        brew install automake zimg
        pip3 install cython

    - name: Use ccache
      if: runner.os == 'linux' || runner.os == 'macos'
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ runner.os }}-${{ inputs.vs-version }}

    - name: Install vapoursynth
      if: runner.os == 'linux'
      shell: bash
      run: |
        export PATH="/usr/lib/ccache:$PATH"
        git clone https://github.com/vapoursynth/vapoursynth --depth 1 -b ${{ inputs.vs-version }}
        pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/usr --disable-x86-asm --disable-vspipe
        make -j2
        sudo make install -j2
        debmake
        debuild
        popd

    - name: Install vapoursynth
      if: runner.os == 'macos'
      shell: bash
      run: |
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
        git clone https://github.com/vapoursynth/vapoursynth --depth 1 -b ${{ inputs.vs-version }}
        pushd vapoursynth
        ./autogen.sh
        ./configure --disable-x86-asm --disable-vspipe
        make -j3
        make install -j3
        popd
