[tool.poetry]
name = "action-setup-vs"
version = "0.0.0"
description = "Action to setup Vapoursynth"
authors = ["DeadNews <deadnewsgit@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
vapoursynth = "^64"
