[tool.poetry]
name = "setup-vapoursynth"
version = "0.0.0"
description = "Action to setup Vapoursynth"
authors = ["DeadNews <aurczpbgr@mozmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
vapoursynth = "^64"
