name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install vapoursynth
        uses: ./

      - name: Test vapoursynth
        run: python -c "import vapoursynth; print(vapoursynth.core.version_number())"