name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  test:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Install Vapoursynth
        uses: ./
