name: Test GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

env:
  LD_LIBRARY_PATH: /usr/local/lib

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install vapoursynth
        uses: ./

      - name: Check `import vapoursynth`
        run: python -c "import vapoursynth; print(vapoursynth.core.version_number())"
