name: Test GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  test-action:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Install vapoursynth
        uses: ./

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install vapoursynth (pip)
      #   run: pip install vapoursynth

      - name: Check `import vapoursynth`
        run: python -c "import vapoursynth; print(vapoursynth.core.version_number())"
