name: Test GitHub Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [created]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: "3.10"

      - name: Install vapoursynth
        uses: ./

      # - name: Install vapoursynth (pip)
      #   run: pip install vapoursynth

      # - name: Check `import vapoursynth`
      #   run: python -c "import vapoursynth; print(vapoursynth.core.version_number())"
